Increase the smarts of the MIME type auto-detection to handle known file extensions specified in mixed case (which may not match the likely lower case definition from your config file).
* mimetype/impl/src/java/org/apache/fulcrum/mimetype/util/MimeTypeMap.java
  getContentType(File): Improved JavaDoc.

  getContentType(String): Leverage new parseFileExtension(String)
  method to simplify and reduce quantity of logic.  Improved JavaDoc.

  getContentType(String, String): Leverage new
  parseFileExtension(String) method and renamed "mime" local variable
  to "mimeType" to improve clarity.

  parseFileExtension(String): File extension parsing logic factored
  out of getContentType() methods.


* mimetype/impl/src/java/org/apache/fulcrum/mimetype/util/MimeTypeMapper.java
  getContentType(String): If an attempted mapping doesn't initially
  resolve, try again with a lowercased file extension (if the original
  extension was mixed case).


* mimetype/impl/src/test/org/apache/fulcrum/mimetype/MimetypeTest.java
  Corrected JavaDoc.

  mimeType, fileExtensions: Moved constants into MimeTypeMapperTest.

  setUp(): Added setting of content type.

  testSetGetContentType(): Rewrote to leverage constants defined in
  MimeTypeMapperTest.

  testGetDefaultExtension(): Used constants now defined in
  MimeTypeMapperTest.

  Note that I could not test this class with
  merlin-plugin-1.1-SNAPSHOT, merlin-unit-3.2.10,
  avalon-extension-impl-1.1, and avalon-extension-spi-1.1 due to the
  following exception:

    java.lang.IllegalArgumentException: Bad specification version
    format '1.0-alpha-4' in 'fulcrum-mimetype-api'. (Reason:
    java.lang.NumberFormatException: For input string: "0-alpha-4")
    org.apache.avalon.extension.Extension.<init>(Extension.java:444)
    ...
    org.apache.avalon.merlin.unit.AbstractMerlinTestCase.setUp(AbstractMerlinTestCase.java:198)
    ...

  This has something to do with the format of the version number used
  in both the Avalon block.xml used while running the tests, which is
  repeated in mimetype-impl's project.xml.  The test case for the
  following class ran fine (as no Avalon init necessary), so I was
  able to verify the core of the change.


* mimetype/impl/src/test/org/apache/fulcrum/mimetype/util/MimeTypeMapperTest.java
  MIME_TYPE, KNOWN_EXTENSIONS, INPUT_EXTENSIONS: New constants
  containing the MIME mapping information used by this and the
  MimetypeTest classes.

  mtm: New instance var to use throughout this test.

  setUp(): Init "mtm".

  testGetSetContentType(): Refactored for brevity and simplicity,
  leveraging constants.

  testGetDefaultExtension(): Stubbed out method (currently commented
  out), and noted that it's mis-placed.


Issue: CollabNet PCN27885


git-svn-id: https://svn.apache.org/repos/asf/jakarta/turbine/fulcrum/trunk/mimetype@223009 13f79535-47bb-0310-9956-ffa450edef68